[package]
name = "fuzz"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
honggfuzz = "0.5.58"
cairo-lang-sierra.workspace = true
cairo-native = { workspace = true, features = ["testing"]}
serde_json.workspace = true
