[package]
name = "fuzz"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
honggfuzz = "0.5.58"
cairo-native = { workspace = true, features = ["testing"]}
