[package]
name = "melior-asm-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.15"

[dependencies.melior-next]
path = "../melior-next"

[dependencies.proc-macro2]
features = ["span-locations"]
version = "1.0.56"
