[book]
authors = ["LambdaClass"]
language = "en"
multilingual = false
src = "src"
title = "Denwen Documentation"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/lambdaclass/cairo_sierra_2_MLIR/edit/main/docs/{path}"
